// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dufrrvnxxokvopoyfutw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1ZnJydm54eG9rdm9wb3lmdXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTIxMzgsImV4cCI6MjA1ODc4ODEzOH0.dNI5zCEaZAk_q9I0liOiDRD_7ciJd5DvybBxYt0SekM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);