// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read variables from environment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Basic check to ensure variables are loaded
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase URL or Anon Key is missing. Make sure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in your .env.local file.");
  // Optionally, throw an error or handle this case appropriately
  // throw new Error("Supabase environment variables are not set.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Initialize client only if variables are present
export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
  : null; // Or handle the absence of keys as needed

// Add a function to check client availability if needed elsewhere
export const isSupabaseConnected = (): boolean => {
  return supabase !== null;
};