// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Try to get variables from environment first
let SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
let SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// If environment variables are not available, fall back to hardcoded values
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("Environment variables not found, falling back to hardcoded values");
  SUPABASE_URL = "https://dufrrvnxxokvopoyfutw.supabase.co";
  SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1ZnJydm54eG9rdm9wb3lmdXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDUxMTAsImV4cCI6MjA2MDAyMTExMH0.Q8DQ2gvPA8Vws4JttHPKAEZUSPcRaLBpqLMJ-aw1rlk";
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Always create a client with either environment variables or hardcoded fallbacks
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a function to check client availability if needed elsewhere
export const isSupabaseConnected = (): boolean => {
  return !!supabase;
};
